### ISSUE TITLE
README states ecmaFeatures.blockBindings is opt-in, but doesn't seem so; can't opt out

### ISSUE THREAD

**Issue by nickiaconis** [eslint/espree#307]
The README states:

> `let` and `const` declarations are no longer parsed by default. You must opt-in using `ecmaFeatures.blockBindings`.

However, it seems that `ecmaFeatures.blockBindings` is turned on by default, and that there is no way to opt out.

I am using Espree via ESLint. This is my `.eslintrc.yml`:

```yaml
extends:
  - eslint:recommended

parserOptions:
  sourceType: module
  ecmaFeatures:
    blockBindings: false
```

I have a `let` declaration in one of the files I am linting, but I do not see any errors.

At the end of the day, what I need is ES5 + import/export. Is there some other way to achieve this?
